export const colorsProtanopia = {
  light: {
    background: '#F7FAFC',
    card: '#FFFFFF',
    appLayoutCard: '#FFFFFF',
    mainBlockBg: '#E3F2FD',

    text: '#1A202C',
    border: '#CBD5E0',
    accent: '#3182CE',
    danger: '#D82C2C',
    warning: '#D69E2E', 
    success: '#2B6CB0', 
    help: '#EDF2F7',
    btnPrimary: '#3182CE',
    btnSecondary: '#2B6CB0', 
    btnDanger: '#D82C2C',
    btnText: '#FFF',

    headerBg: '#2B6CB0',
    headerText: '#FFF',
    headerBtnBg: '#3182CE',
    headerBtnText: '#FFF',
    helpBtnBg: '#E3F2FD',
    helpBtnText: '#1A202C',

    inputBg: '#F7FAFC',
    inputBorder: '#CBD5E0',
    inputText: '#1A202C',
    inputPlaceholder: '#A0AEC0',
    inputIcon: '#3182CE',
    inputError: '#D82C2C',
    inputFocus: '#3182CE',
    inputIconCircle: '#3182CE',
    inputLinkText: '#3182CE',

    listaEventosSearchBar: '#E3F2FD',
    listaEventosCard: '#FFFFFF',
    listaEventosIcon: '#3182CE',
    listaEventosNombre: '#1A202C',
    listaEventosFecha: '#718096',
    listaEventosBtnEditar: '#2B6CB0', 
    listaEventosBtnBorrar: '#D82C2C',
    listaEventosBtnVer: '#3182CE',
    listaEventosBtnIcon: '#FFF',

    formFotosBlock: '#E3F2FD',
    formFotoRow: '#FFFFFF',
    formFotoRowBorder: '#CBD5E0',
    formAddBtn: '#2B6CB0',
    formAddBtnText: '#FFF',
    formBtnDanger: '#D82C2C',
    formBtnDangerText: '#FFF',
    formBtnPrimary: '#3182CE',
    formBtnPrimaryText: '#FFF',
    formBtnSecondary: '#2B6CB0',

    appLayoutBg: '#F7FAFC',
    appLayoutGreenBlock: '#E3F2FD',
    appLayoutRegresarBtn: '#3182CE',
    appLayoutRegresarBtnText: '#FFF',

    homeCardBg: '#FFFFFF',
    homeBtnText: '#3182CE',

    tomarFotoBtnBg: '#3182CE',
    tomarFotoBtnText: '#FFF',
    tomarFotoPreviewBorder: '#CBD5E0',
    tomarFotoRegresarBtnBg: '#2B6CB0',
    tomarFotoRegresarBtnText: '#FFF',

    editarEventoGreenBlock: '#E3F2FD',
    editarEventoRegresarBtn: '#3182CE',
    editarEventoRegresarBtnText: '#FFF',
    editarEventoOpcion1Bg: '#F7FAFC',
    editarEventoOpcion2Bg: '#F7FAFC',
    editarEventoOpcion3Bg: '#F7FAFC',
    editarEventoOpcionText: '#1A202C',
    editarEventoIcon1Bg: '#3182CE',
    editarEventoIcon2Bg: '#2B6CB0', 
    editarEventoIcon3Bg: '#D69E2E',

    configSectionBg: '#FFFFFF',
    configColorOptionBg: '#E3F2FD',
    configColorOptionSelected: '#2B6CB0',
    configColorRadio: '#CBD5E0',
    configColorRadioSelected: '#3182CE',
    configFontBtn: '#3182CE',
    configFontBtnText: '#FFF',
    configLabelText: '#1A202C',

    historialMainBg: '#F7FAFC',
    historialCardBg: '#FFFFFF',
    eventoCard: '#FFFFFF',
    btnIcon: '#3182CE',
    eventoNombre: '#1A202C',
    eventoFecha: '#718096',
    btnEditar: '#2B6CB0',
    btnBorrar: '#D82C2C',
    btnVer: '#3182CE',
    iconTendencias: '#2B6CB0',

    TomarFoto: {
      cameraBtnBg: '#3182CE',
      cameraBtnText: '#FFF',
      previewBorder: '#CBD5E0',
      regresarBtnBg: '#2B6CB0',
      regresarBtnText: '#FFF',
    },

    EditarEvento: {
      greenBlock: '#E3F2FD',
      regresarBtn: '#3182CE',
      regresarBtnText: '#FFF',
      opcion1Bg: '#F7FAFC',
      opcion2Bg: '#F7FAFC',
      opcion3Bg: '#F7FAFC',
      opcionText: '#1A202C',
      icon1Bg: '#3182CE',
      icon2Bg: '#2B6CB0',
      icon3Bg: '#D69E2E',
    },

    Config: {
      sectionBg: '#FFFFFF',
      colorOptionBg: '#E3F2FD',
      colorOptionSelected: '#2B6CB0',
      colorRadio: '#CBD5E0',
      colorRadioSelected: '#3182CE',
      fontBtn: '#3182CE',
      fontBtnText: '#FFF',
      labelText: '#1A202C',
    },

    iconCircle: '#E3F2FD',
    iconCircleIcon: '#3182CE',

    loginBtnBg: '#2B6CB0',
    loginBtnText: '#FFF',
    loginLinkText: '#1A202C',
    loginCreateBtnBg: '#2B6CB0',
    loginCreateBtnText: '#FFF',
    loginIconColor: '#3182CE',

    themedText: {
      default: '#3182CE',
      title: '#2B6CB0',
      link: '#3182CE',
      subtitle: '#1A202C',
      defaultSemiBold: '#1A202C',
    },
    themedView: '#F7FAFC',
    externalLink: '#3182CE',
    formIconCircle: '#E3F2FD',
    formIconCircleIcon: '#3182CE',
    collapsible: {
      background: '#F7FAFC',
      headerText: '#3182CE',
      icon: '#3182CE',
    },
    historialArchivoIconBg: '#2B6CB0',
    historialArchivoIconColor: '#FFF',
    historialEditarIconBg: '#2B6CB0',
    historialEditarIconColor: '#FFF',
    historialBorrarIconBg: '#D82C2C',
    historialBorrarIconColor: '#FFF',
    historialObservarIconBg: '#2B6CB0',
    historialObservarIconColor: '#FFF',
    ResultadoAsistencia: {
      infoInputBg: '#e8f5e9',
      infoInputBorder: '#b4cded',
      infoInputText: '#1A202C',
      previewBlockBg: '#e8f5e9',
      previewTitle: '#2B6CB0',
      excelContainerBorder: '#2B6CB0',
      excelContainerBg: '#e8f5e9',
      tablaBorder: '#b4cded',
      tablaBg: '#fff',
      tablaHeaderText: '#2B6CB0',
      tablaCellText: '#222',
      tablaRowBorder: '#b4cded',
      nombreIndex: '#2B6CB0',
      nombreText: '#222',
      btnCancelarBg: '#3182CE',
      btnCancelarText: '#fff',
      btnContinuarBg: '#2B6CB0',
      btnContinuarText: '#fff',
      checkIcon: '#2B6CB0',
    },
  },
  dark: {
    background: '#1A202C',
    card: '#2D3748',
    appLayoutCard: '#2D3748',
    mainBlockBg: '#1E365D',

    text: '#E2E8F0',
    border: '#4A5568',
    accent: '#63B3ED',
    danger: '#F56565', 
    warning: '#D69E2E',
    success: '#4299E1',
    help: '#2D3748',
    btnPrimary: '#63B3ED',
    btnSecondary: '#4299E1',
    btnDanger: '#F56565',
    btnText: '#FFF',

    headerBg: '#1E4B8C',
    headerText: '#FFF',
    headerBtnBg: '#63B3ED',
    headerBtnText: '#FFF',
    helpBtnBg: '#2D3748',
    helpBtnText: '#CBD5E0',

    inputBg: '#2D3748',
    inputBorder: '#4A5568',
    inputText: '#E2E8F0',
    inputPlaceholder: '#B3C7E6',
    inputIcon: '#63B3ED',
    inputError: '#F56565',
    inputFocus: '#63B3ED',
    inputIconCircle: '#63B3ED',
    inputLinkText: '#90CDF4',

    listaEventosSearchBar: '#1E365D',
    listaEventosCard: '#2D3748',
    listaEventosIcon: '#63B3ED',
    listaEventosNombre: '#E2E8F0',
    listaEventosFecha: '#718096',
    listaEventosBtnEditar: '#4299E1', 
    listaEventosBtnBorrar: '#F56565',
    listaEventosBtnVer: '#63B3ED',
    listaEventosBtnIcon: '#FFF',

    formFotosBlock: '#1E365D',
    formFotoRow: '#2D3748',
    formFotoRowBorder: '#4A5568',
    formAddBtn: '#4299E1',
    formAddBtnText: '#FFF',
    formBtnDanger: '#F56565',
    formBtnDangerText: '#FFF',
    formBtnPrimary: '#63B3ED',
    formBtnPrimaryText: '#FFF',
    formBtnSecondary: '#4299E1',

    appLayoutBg: '#1A202C',
    appLayoutGreenBlock: '#1E365D',
    appLayoutRegresarBtn: '#63B3ED',
    appLayoutRegresarBtnText: '#FFF',

    homeCardBg: '#2D3748',
    homeBtnText: '#63B3ED',

    tomarFotoBtnBg: '#63B3ED',
    tomarFotoBtnText: '#FFF',
    tomarFotoPreviewBorder: '#4A5568',
    tomarFotoRegresarBtnBg: '#4299E1',
    tomarFotoRegresarBtnText: '#FFF',

    editarEventoGreenBlock: '#1E365D',
    editarEventoRegresarBtn: '#63B3ED',
    editarEventoRegresarBtnText: '#FFF',
    editarEventoOpcion1Bg: '#2D3748',
    editarEventoOpcion2Bg: '#2D3748',
    editarEventoOpcion3Bg: '#2D3748',
    editarEventoOpcionText: '#E2E8F0',
    editarEventoIcon1Bg: '#63B3ED',
    editarEventoIcon2Bg: '#4299E1',
    editarEventoIcon3Bg: '#D69E2E',

    configSectionBg: '#2D3748',
    configColorOptionBg: '#1E365D',
    configColorOptionSelected: '#4299E1',
    configColorRadio: '#4A5568',
    configColorRadioSelected: '#63B3ED',
    configFontBtn: '#63B3ED',
    configFontBtnText: '#FFF',
    configLabelText: '#E2E8F0',

    historialMainBg: '#1A202C',
    historialCardBg: '#2D3748',
    eventoCard: '#2D3748',
    btnIcon: '#63B3ED',
    eventoNombre: '#E2E8F0',
    eventoFecha: '#718096',
    btnEditar: '#4299E1',
    btnBorrar: '#F56565',
    btnVer: '#63B3ED',
    iconTendencias: '#4299E1',

    TomarFoto: {
      cameraBtnBg: '#63B3ED',
      cameraBtnText: '#FFF',
      previewBorder: '#4A5568',
      regresarBtnBg: '#4299E1',
      regresarBtnText: '#FFF',
    },

    EditarEvento: {
      greenBlock: '#1E365D',
      regresarBtn: '#63B3ED',
      regresarBtnText: '#FFF',
      opcion1Bg: '#2D3748',
      opcion2Bg: '#2D3748',
      opcion3Bg: '#2D3748',
      opcionText: '#E2E8F0',
      icon1Bg: '#63B3ED',
      icon2Bg: '#4299E1',
      icon3Bg: '#D69E2E',
    },

    Config: {
      sectionBg: '#2D3748',
      colorOptionBg: '#1E365D',
      colorOptionSelected: '#4299E1',
      colorRadio: '#4A5568',
      colorRadioSelected: '#63B3ED',
      fontBtn: '#63B3ED',
      fontBtnText: '#FFF',
      labelText: '#E2E8F0',
    },

    iconCircle: '#2D3748',
    iconCircleIcon: '#4299E1',

    loginBtnBg: '#4299E1',
    loginBtnText: '#FFF',
    loginLinkText: '#FFF',
    loginCreateBtnBg: '#4299E1',
    loginCreateBtnText: '#FFF',
    loginIconColor: '#63B3ED',

    themedText: {
      default: '#63B3ED',
      title: '#4299E1',
      link: '#63B3ED',
      subtitle: '#CBD5E0',
      defaultSemiBold: '#E2E8F0',
    },
    themedView: '#1A202C',
    externalLink: '#4299E1',
    formIconCircle: '#2D3748',
    formIconCircleIcon: '#4299E1',
    collapsible: {
      background: '#1A202C',
      headerText: '#4299E1',
      icon: '#4299E1',
    },
    historialArchivoIconBg: '#4299E1',
    historialArchivoIconColor: '#1A202C',
    historialEditarIconBg: '#4299E1',
    historialEditarIconColor: '#1A202C',
    historialBorrarIconBg: '#F56565',
    historialBorrarIconColor: '#1A202C',
    historialObservarIconBg: '#4299E1',
    historialObservarIconColor: '#1A202C',
    ResultadoAsistencia: {
      infoInputBg: '#1E365D',
      infoInputBorder: '#4299E1',
      infoInputText: '#E2E8F0',
      previewBlockBg: '#1E365D',
      previewTitle: '#4299E1',
      excelContainerBorder: '#4299E1',
      excelContainerBg: '#1E365D',
      tablaBorder: '#4299E1',
      tablaBg: '#2D3748',
      tablaHeaderText: '#4299E1',
      tablaCellText: '#E2E8F0',
      tablaRowBorder: '#4299E1',
      nombreIndex: '#4299E1',
      nombreText: '#E2E8F0',
      btnCancelarBg: '#63B3ED',
      btnCancelarText: '#fff',
      btnContinuarBg: '#4299E1',
      btnContinuarText: '#1A202C',
      checkIcon: '#4299E1',
    },
  },
};

export default colorsProtanopia;