export const colorsHighContrast = {
  light: {
    text: '#000',
    background: '#FFF',
    card: '#FFF',
    border: '#000',
    accent: '#0000FF',
    danger: '#FF0000',
    warning: '#FFD700',
    success: '#008000',
    help: '#FFF',
    btnPrimary: '#0000FF',
    btnSecondary: '#008000',
    btnDanger: '#FF0000',
    btnText: '#FFF',

    headerBg: '#0000FF',
    headerText: '#FFF',
    headerBtnBg: '#0000FF',
    headerBtnText: '#FFF',
    helpBtnBg: '#FFF',
    helpBtnText: '#000',

    inputBg: '#FFF',
    inputBorder: '#000',
    inputText: '#000',
    inputPlaceholder: '#000',
    inputIcon: '#0000FF',
    inputError: '#FF0000',
    inputFocus: '#0000FF',

    inputIconCircle: '#0000FF',
    inputLinkText: '#0000FF',

    listaEventosSearchBar: '#FFF',
    listaEventosCard: '#FFF',
    listaEventosIcon: '#0000FF',
    listaEventosNombre: '#000',
    listaEventosFecha: '#000',
    listaEventosBtnEditar: '#008000',
    listaEventosBtnBorrar: '#FF0000',
    listaEventosBtnVer: '#0000FF',
    listaEventosBtnIcon: '#FFF',

    formFotosBlock: '#FFF',
    formFotoRow: '#FFF',
    formFotoRowBorder: '#000',
    formAddBtn: '#FFD700',
    formAddBtnText: '#000',
    formBtnDanger: '#FF0000',
    formBtnDangerText: '#FFF',
    formBtnPrimary: '#008000',
    formBtnPrimaryText: '#FFF',
    formBtnSecondary: '#0000FF',

    appLayoutBg: '#FFF',
    appLayoutCard: '#FFF',
    appLayoutGreenBlock: '#FFD700',
    appLayoutRegresarBtn: '#0000FF',
    appLayoutRegresarBtnText: '#FFF',

    homeCardBg: '#FFF',
    homeBtnText: '#0000FF',

    tomarFotoBtnBg: '#0000FF',
    tomarFotoBtnText: '#FFF',
    tomarFotoPreviewBorder: '#000',
    tomarFotoRegresarBtnBg: '#008000',
    tomarFotoRegresarBtnText: '#FFF',

    editarEventoGreenBlock: '#FFD700',
    editarEventoRegresarBtn: '#0000FF',
    editarEventoRegresarBtnText: '#FFF',
    editarEventoOpcionBg: '#FFF',
    editarEventoOpcionText: '#000',
    editarEventoIconBg: '#0000FF',

    historialMainBg: '#FFF',
    historialCardBg: '#FFF',

    configSectionBg: '#FFF',
    configColorOptionBg: '#FFD700',
    configColorOptionSelected: '#0000FF',
    configColorRadio: '#000',
    configColorRadioSelected: '#0000FF',
    configFontBtn: '#0000FF',
    configFontBtnText: '#FFF',
    configLabelText: '#000',

    eventoCard: '#FFF',
    btnIcon: '#0000FF',
    eventoNombre: '#000',
    eventoFecha: '#000',
    btnEditar: '#008000',
    btnBorrar: '#FF0000',
    btnVer: '#0000FF',
    iconTendencias: '#FFD700',

    TomarFoto: {
      cameraBtnBg: '#0000FF',
      cameraBtnText: '#FFF',
      previewBorder: '#000',
      regresarBtnBg: '#008000',
      regresarBtnText: '#FFF',
    },

    EditarEvento: {
      greenBlock: '#FFD700',
      regresarBtn: '#0000FF',
      regresarBtnText: '#FFF',
      opcion1Bg: '#FFF',
      opcion2Bg: '#FFF',
      opcion3Bg: '#FFF',
      opcionText: '#000',
      icon1Bg: '#0000FF',
      icon2Bg: '#008000',
      icon3Bg: '#FFD700',
    },

    Config: {
      sectionBg: '#FFF',
      colorOptionBg: '#FFD700',
      colorOptionSelected: '#0000FF',
      colorRadio: '#000',
      colorRadioSelected: '#0000FF',
      fontBtn: '#0000FF',
      fontBtnText: '#FFF',
      labelText: '#000',
    },

    editarEventoOpcion1Bg: '#FFF',
    editarEventoOpcion2Bg: '#FFF',
    editarEventoOpcion3Bg: '#FFF',
    editarEventoIcon1Bg: '#0000FF',
    editarEventoIcon2Bg: '#008000',
    editarEventoIcon3Bg: '#FFD700',

    btnDangerText: '#FFF',
  },
  dark: {
    text: '#000',
    background: '#FFFFE0',
    card: '#FFF',
    border: '#000',
    accent: '#0000FF',
    danger: '#FF0000',
    warning: '#FFD700',
    success: '#008000',
    help: '#FFFFE0',
    btnPrimary: '#0000FF',
    btnSecondary: '#008000',
    btnDanger: '#FF0000',
    btnText: '#000',

    headerBg: '#0000FF',
    headerText: '#FFF',
    headerBtnBg: '#0000FF',
    headerBtnText: '#FFF',
    helpBtnBg: '#FFFFE0',
    helpBtnText: '#000',

    inputBg: '#FFFFE0',
    inputBorder: '#000',
    inputText: '#000',
    inputPlaceholder: '#000',
    inputIcon: '#0000FF',
    inputError: '#FF0000',
    inputFocus: '#0000FF',

    inputIconCircle: '#0000FF',
    inputLinkText: '#0000FF',

    listaEventosSearchBar: '#FFFFE0',
    listaEventosCard: '#FFF',
    listaEventosIcon: '#0000FF',
    listaEventosNombre: '#000',
    listaEventosFecha: '#000',
    listaEventosBtnEditar: '#008000',
    listaEventosBtnBorrar: '#FF0000',
    listaEventosBtnVer: '#0000FF',
    listaEventosBtnIcon: '#000',

    formFotosBlock: '#FFFFE0',
    formFotoRow: '#FFF',
    formFotoRowBorder: '#000',
    formAddBtn: '#FFD700',
    formAddBtnText: '#000',
    formBtnDanger: '#FF0000',
    formBtnDangerText: '#FFF',
    formBtnPrimary: '#008000',
    formBtnPrimaryText: '#FFF',
    formBtnSecondary: '#0000FF',

    appLayoutBg: '#FFFFE0',
    appLayoutCard: '#FFF',
    appLayoutGreenBlock: '#FFD700',
    appLayoutRegresarBtn: '#0000FF',
    appLayoutRegresarBtnText: '#FFF',

    homeCardBg: '#FFF',
    homeBtnText: '#0000FF',

    tomarFotoBtnBg: '#0000FF',
    tomarFotoBtnText: '#FFF',
    tomarFotoPreviewBorder: '#000',
    tomarFotoRegresarBtnBg: '#008000',
    tomarFotoRegresarBtnText: '#FFF',

    editarEventoGreenBlock: '#FFD700',
    editarEventoRegresarBtn: '#0000FF',
    editarEventoRegresarBtnText: '#FFF',
    editarEventoOpcionBg: '#FFFFE0',
    editarEventoOpcionText: '#000',
    editarEventoIconBg: '#0000FF',

    historialMainBg: '#FFFFE0',
    historialCardBg: '#FFF',

    configSectionBg: '#FFFFE0',
    configColorOptionBg: '#FFD700',
    configColorOptionSelected: '#0000FF',
    configColorRadio: '#000',
    configColorRadioSelected: '#0000FF',
    configFontBtn: '#0000FF',
    configFontBtnText: '#FFF',
    configLabelText: '#000',

    eventoCard: '#FFF',
    btnIcon: '#0000FF',
    eventoNombre: '#000',
    eventoFecha: '#000',
    btnEditar: '#008000',
    btnBorrar: '#FF0000',
    btnVer: '#0000FF',
    iconTendencias: '#FFD700',

    TomarFoto: {
      cameraBtnBg: '#0000FF',
      cameraBtnText: '#FFF',
      previewBorder: '#000',
      regresarBtnBg: '#008000',
      regresarBtnText: '#FFF',
    },

    EditarEvento: {
      greenBlock: '#FFD700',
      regresarBtn: '#0000FF',
      regresarBtnText: '#FFF',
      opcion1Bg: '#FFFFE0',
      opcion2Bg: '#FFFFE0',
      opcion3Bg: '#FFFFE0',
      opcionText: '#000',
      icon1Bg: '#0000FF',
      icon2Bg: '#008000',
      icon3Bg: '#FFD700',
    },

    Config: {
      sectionBg: '#FFFFE0',
      colorOptionBg: '#FFD700',
      colorOptionSelected: '#0000FF',
      colorRadio: '#000',
      colorRadioSelected: '#0000FF',
      fontBtn: '#0000FF',
      fontBtnText: '#FFF',
      labelText: '#000',
    },

    editarEventoOpcion1Bg: '#FFFFE0',
    editarEventoOpcion2Bg: '#FFFFE0',
    editarEventoOpcion3Bg: '#FFFFE0',

    editarEventoIcon1Bg: '#0000FF',
    editarEventoIcon2Bg: '#008000',
    editarEventoIcon3Bg: '#FFD700',

    btnDangerText: '#FFF',
  },
};
